export const SUCCESS_RESPONSE = "success";
export const ERROR_RESPONSE_UNAUTHORIZED = "Unauthorized";
export const ERROR_RESPONSE_INTERNAL_SERVER_ERROR = "Internal server error";
export const STATUS_CODE_OK = 200;
export const STATUS_CODE_CREATED = 201;
export const STATUS_CODE_BAD_REQUEST = 400;
export const STATUS_CODE_UNAUTHORIZED = 401;
export const STATUS_CODE_NOT_FOUND = 404;
export const STATUS_CODE_INTERNAL_SERVER_ERROR = 500;
